### ISSUE TITLE
[Suggestion] remember checkbox settings

### ISSUE THREAD

**Issue by Zarremgregarrok** [lyneca/eidoclock#10]
Greetings,
Have you considered storing state of `Pretty background` and `Show scaled time` in a cookie or some other local storage?
I find the scaled time rather annoying how fast it is changing and it would be awesome not having to disable it every time I reload the page.

**Comment by Alexander-Poganatz** [comment]
I'll look into it. I'm thinking about using local storage.

I am also planning to adjust the update interval so when scaled time is not showing the update routine will execute every 100+ms instead of every 1ms since updating every possible millisecond consumes to much system resources.

**Comment by Alexander-Poganatz** [comment]
Changes are now merged, this issue can be closed if no bugs arise.
