### ISSUE TITLE
Marker for current time approaching Night is off

### ISSUE THREAD

**Issue by esunder** [lyneca/eidoclock#14]
Just noticed this, it is almost time for night to begin and the marker on the right has passed the "Night starts" marker. I assume we want the marker to line up with the text as the transition to night happens?

https://puu.sh/BKWHP/6a02a3a663.png

**Comment by Alexander-Poganatz** [comment]
Your assumption sounds correct to me. I also noticed it loops around to the day start when there is still a few minutes of night left too.

**Comment by lyneca** [comment]
Yeah I kinda just eyeballed that when I made it - it was "good enough" when it was just me using the site.

**Comment by lyneca** [comment]
This should be fixed with the rewrite.
