### ISSUE TITLE
issue with mobile screens

### ISSUE THREAD

**Issue by nonchip** [lyneca/eidoclock#16]
on my phone (chromium on android on a 1:2 "super-portrait" screen) the css breaks, making the timer at the top unreadable.

screenshot: https://ibb.co/igCiaf

this looks to be an issue with the specific media query and font sizes making it wrap in a weird way introducing too much space at the top

**Comment by Alexander-Poganatz** [comment]
This issue seems to be introduced with the recent addition of future times from issue #14 .

**Comment by Alexander-Poganatz** [comment]
I'll take a stab at it.

**Comment by Alexander-Poganatz** [comment]
I got pull request #17 up

**Comment by nonchip** [comment]
yep works fine now :)
