### ISSUE TITLE
Website is completely nonfunctional.

### ISSUE THREAD

**Issue by kbelcher3** [lyneca/eidoclock#26]
I have tried several browsers and all I see is something like this: https://i.imgur.com/DR1Y0r4.png

**Comment by Delfic** [comment]
https://us-central1-eidoclock.cloudfunctions.net/getTime
This is returning
"Runtime nodejs6 is no longer available. Please redeploy your function to a newer version."

**Comment by lyneca** [comment]
Hey, I'm no longer maintaining this tool out of lack of interest and lack of time.

There are other, better tools available, such as this one: https://wflists.net/clock/
