### ISSUE TITLE
Clock is running late by 17 minutes

### ISSUE THREAD

**Issue by Wampa842** [lyneca/eidoclock#3]
Today I was playing on the Plains and noticed that when the Teralyst retreats into the water and the Cetus bounties reset, the website shows that sunrise wouldn't come for another 17 minutes.

The issue can be fixed by changing line 49 in clock.js to:
`var start_time = (1510894634 - 150 * 60) - 10 * 60 + 18;`

Alternatively:
`var start_time = 1510885052;`

I checked both in a clone and they show the correct time.

**Comment by lyneca** [comment]
Thanks! Feel free to make a PR.
