### ISSUE TITLE
[Suggestion]  Show the next nights in 24h.

### ISSUE THREAD

**Issue by GleitonCampos** [lyneca/eidoclock#9]
A suggestion is the page show the current time of the visitor PC and use a calculator to show us the next night times in 24h or more. Will be a nice function to people that work and/or study to know if when we arrive, what time of day will be available.

**Comment by Alexander-Poganatz** [comment]
Seems like a neat idea. I'll start investigating the possibility.
I would imagine the general routine would be calculating the next night time and then adding 150 minutes until the next 24 hour mark. 
I'm also going to grab some Cetus bounty times to see if there is a straight 150 minute difference between bounty expire dates.

I would also like some suggestions on the data view. Should it be separate page? Add a switch on the bottom to change from timer view to forecast view? and so on.

**Comment by esunder** [comment]
Is this actively being worked on? I'd be interested in helping as part of Hacktoberfest, but dont want to encroach on someone else's progress.

**Comment by lyneca** [comment]
You have my blessing!

**Comment by Alexander-Poganatz** [comment]
Sure go ahead. I stopped working on it after receiving no feedback.
